mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from polls.sitemaps import StaticViewSitemap, SnippetSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
'static': StaticViewSitemap,
'snippet': SnippetSitemap,
}

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
]

polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    
    path('graph/', views.graph, name='graph'),
    path('', views.index, name='index'),
    path('mail/', views.mail, name='mail'),
    path('main/', views.mainPage, name='main'),
    path('AddAddress/', views.addAddress, name='AddAddress'),
    path('checkout/', views.checkout, name='checkout'),
    path('myAccount/', views.myAccount, name='myAccount'),
    path('categoryFemale/', views.categoryFemale, name='categoryFemale'),
    path('categoryMale/', views.categoryMale, name='categoryMale'),
    path('category/', views.category, name='category'),
    path('signIn/', views.signIn, name='signIn'),
    path('signUp/', views.signUp, name='signUp'),
    path('create/', views.create, name='create' ),
    path('authenticate/', views.authenticate, name='authenticate' ),
    path('signOut/', views.signOut, name='signOut' ),
    path('addCart/<int:id>/', views.addCart, name='addCart' ),
    path('deletecart/<id>/', views.deletecart, name='deletecart' ),
    path('invoice/', views.invoice, name='invoice' ),

    path('addCustomer/', views.addCustomer, name='addCustomer' ),
    path('manageCustomer/', views.manageCustomer, name='manageCustomer'), 
    path('update/<int:id>/', views.update, name='update' ),
    path('edit/<int:id>/', views.edit, name='edit' ),   
    path('addUser/', views.addUser, name='addUser' ),
    #form
    path('catForm/', views.categoryFormView, name='categoryFormView'),
    #SiteMap
    path('about/', views.about, name='about'),
    path('<slug:slug>/', views.snippet_detail),
    
]

polls/models.py
from django.db import models
from django.utils.text import slugify
from django.shortcuts import reverse


MALE, FEMALE = range(2)
GENDER = (
    (MALE, 'MALE'),
    (FEMALE, 'FEMALE')
)

CHINESE, SPANISH, ENGLISH, FRENCH, HINDI, ARABIC, RUSSIAN = range(7)
LANGUAGES = (
    (CHINESE, 'CHINESE'),
    (SPANISH, 'SPANISH'),
    (ENGLISH, 'ENGLISH'),
    (FRENCH, 'FRENCH'),
    (HINDI, 'HINDI'),
    (ARABIC, 'ARABIC'),
    (RUSSIAN, 'RUSSIAN'),
)


class Student(models.Model):
    full_name = models.CharField('Full Name', max_length=50)
    gender = models.PositiveSmallIntegerField('Gender', choices=GENDER, default=MALE)
    language = models.PositiveSmallIntegerField('Language', choices=LANGUAGES, default=ENGLISH)
    grades = models.CharField('Grades', max_length=2)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = ('Student')
# Create your models here.
class Snippet(models.Model):
    title =models.CharField(max_length=15)
    slug = models.SlugField(blank=True, null=True)
    body = models.TextField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    def get_absolute_url(self):
        return  self.slug

class Customer(models.Model):
    Cust_id = models.AutoField(primary_key=True)
    Cust_name = models.CharField(max_length=255)
    Cust_email = models.CharField(unique=True, max_length=255)
    Cust_password = models.CharField(max_length=255)
    Cust_country = models.CharField(max_length=255)
    Cust_address = models.TextField()
    Cust_phoneNo = models.CharField(max_length=255)
    Cust_postalCode = models.IntegerField()
    def __str__(self):
        return self.Cust_name
    

class Category(models.Model):
    Cat_id = models.AutoField(primary_key=True)
    Cat_type = models.CharField(unique=True, max_length=255)
    Cat_description = models.TextField()
    def __unicode__(self):
        return self.Cat_type

class Product(models.Model):
    P_id = models.AutoField(primary_key=True)
    P_name = models.CharField(max_length=255)
    P_quantity = models.IntegerField()
    P_price = models.IntegerField()
    P_image = models.ImageField()
    Cat_id = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __int__(self):
        return self.P_id
    def __str__(self):
        return self.P_name

    class Meta:
        verbose_name = ('Product')

class Cart(models.Model):
    Cart_id = models.AutoField(primary_key=True)
    Cart_quantity = models.IntegerField()
    Cust_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    P_id = models.ForeignKey(Product, on_delete=models.CASCADE)

class Shipper(models.Model):
    Shipper_id = models.AutoField(primary_key=True)
    Shipper_phoneNo = models.CharField(max_length=25)
    Shipper_CompanyName = models.CharField(max_length=255)

class Order(models.Model):
    Order_id = models.AutoField(primary_key=True)
    Shipper_id = models.ForeignKey(Shipper, on_delete=models.CASCADE)
    Cust_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    P_id = models.ForeignKey(Product, on_delete=models.CASCADE)
class Address(models.Model):
    address_id = models.AutoField(primary_key=True)
    Cust_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    addressTitle = models.CharField(max_length=25)
    HouseNo = models.CharField(max_length=255)
    StreetNo = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
class SaleSummary(Cart):
    class Meta:
        proxy = True
        verbose_name = 'Sale Summary'
        verbose_name_plural = 'Sales Summary'

polls/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Customer
from .models import Product
from .models import Cart, Snippet
from .form import CategoryForm
from django.http import HttpResponse
from django.contrib import messages
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.conf import settings
import array as arr


def categoryFormView(request):
   form =CategoryForm(request.POST or None)
   if form.is_valid():
      form.save()
      form = CategoryForm()
   context = {
      'form' : form 
   }
   return render(request, 'best/formDetail.html', context)

def graph(request):
    return render(request, 'best/sale_summary_change_list.html')
def index(request):
    return render(request, 'best/dashboard.html')

def about(request):
   return HttpResponse("About Page....")

def snippet_detail(request, slug):
   snippet = get_object_or_404(Snippet, slug=slug)
   return HttpResponse('Detail View for slug of {{slug}}')

def create(request):
    print(request.POST)
    cust_name = request.GET['fullname']
    cust_email = request.GET['email']
    cust_password = request.GET['password']
    cust_country = request.GET['country']
    cust_address = request.GET['homeAddress']
    cust_phoneNo = request.GET['phoneNo']
    cust_postalCode = request.GET['postalCode']
    Insert_customer = Customer(Cust_name=cust_name, Cust_email=cust_email, Cust_password=cust_password,
     Cust_country=cust_country, Cust_address=cust_address,Cust_phoneNo=cust_phoneNo, Cust_postalCode=cust_postalCode)
    Insert_customer.save()
    messages.success(request, 'User Register Sucessful')
    return render(request,'best/dashboard.html')
    #return HttpResponse("Hello, world. You're at the polls index.!")

def authenticate(request):
    print(request.POST)
    cust_email = request.GET['email']
    cust_password = request.GET['password']
    customers = Customer.objects.filter(Cust_email=cust_email,Cust_password=cust_password).count()
    
    if customers>0:
        #name = Customer.objects.filter(Cust_email=cust_email).values('Cust_name')
        request.session['email'] = cust_email
        #return HttpResponse(name)
        #request.session['name'] = name.Cust_name
        return render(request,'best/dashboard.html')
    return render(request,'best/SignIn.html')

def signOut(request):
   try:
      del request.session['email']
   except:
      pass
   return render(request,'best/dashboard.html')

def deletecart(request, id):
    cart = Cart.objects.get(pk=id)
    cart.delete()
    return redirect('/checkout')

def addCart(request, id):
   #'loggedin': request.session.get('email')
   if request.session.get('email') != "":
      productInfo = Product.objects.get(pk=id)
      p_id = productInfo.P_id
      c_quantity = 1
      cust_id = Customer.objects.get(Cust_email=request.session.get('email'))
      insert_cart = Cart(Cart_quantity=c_quantity, Cust_id=cust_id, P_id=Product.objects.get(pk=id))
      insert_cart.save()
      return redirect('../../checkout')
      #return render(request,'best/checkout.html')
   else:
      return render(request,'best/SignIn.html')
   #cart = Cart(request)
   #product = get_object_or_404(Product, id=product_id)

def mail(request):
   subject = 'Hello'
   message = 'Hi'
   from_email = settings.EMAIL_HOST_USER
   tmail = [settings.EMAIL_HOST_USER, 'ahmadidrees347@gmail.com']
   send_mail(subject, message, from_email, tmail, fail_silently=True)
   return HttpResponse('Thanku')  

def mainPage(request):
    return render(request,'best/dashboard.html')
def addAddress(request):
    return render(request,'best/AddAddress.html')

def invoice(request):
     if request.POST.get('checkbox'):
        return HttpResponse("OK")
     else:
        #qnty = request.POST.get('qnty')
        #qnty = request.GET['qnty']
        #return HttpResponse("OK"+str(qnty))
        cust_id = Customer.objects.get(Cust_email=request.session.get('email'))
        customers = Customer.objects.filter(Cust_email=request.session.get('email'))
        carts = Cart.objects.filter(Cust_id=cust_id)
        products = Product.objects.all();
        Tprice = 0;
        i=0;
        myList = [];
        obj = Product.objects.all()
        obj.a = lambda: None


        a = arr.array('d', myList)
        for cart in carts:
         for product in products:
            if product.P_id == cart.P_id.P_id:
               total_price = product.P_price*cart.Cart_quantity;
               setattr(obj.a, 'price', total_price)
               product.price = product.P_price*cart.Cart_quantity

               myList.append(product.P_price*cart.Cart_quantity);
               Tprice += total_price;
               i=i+1
        context = {
           'carts': carts,
           'products':products,
           'customers':customers,
           'total_price':total_price,
           'Tprice':Tprice,
           'myList': myList
        }
        #return HttpResponse("OK"+str(context))
        return render(request,'best/invoice.html',context)

def checkout(request):
    cust_id = Customer.objects.get(Cust_email=request.session.get('email'))
    customers = Customer.objects.filter(Cust_email=request.session.get('email'))
    carts = Cart.objects.filter(Cust_id=cust_id)
    products = Product.objects.all();
    context = {
        'carts': carts,
        'products':products,
        'customers':customers
    }
    #return HttpResponse(carts)
    return render(request,'best/checkout.html',context)
def myAccount(request):
    return render(request,'best/My Account.html')
def category(request):
    posts = Product.objects.all()
    paginator = Paginator(posts, 3) # < 3 is the number of items on each page
    page = request.GET.get('page') # < Get the page number

    posts = paginator.get_page(page)
    products = Product.objects.all()
    context = {
        'products': products,
        'posts': posts
    }
    #return HttpResponse(products)
    return render(request,'best/category.html',context)
def categoryFemale(request):
    posts = Product.objects.filter(Cat_id=2)
    paginator = Paginator(posts, 3) # < 3 is the number of items on each page
    page = request.GET.get('page') # < Get the page number

    posts = paginator.get_page(page)
    products = Product.objects.all()
    context = {
        'products': products,
        'posts': posts
    }
    #return HttpResponse(products)
    return render(request,'best/category.html',context)
def categoryMale(request):
    posts = Product.objects.filter(Cat_id=1)
    paginator = Paginator(posts, 3) # < 3 is the number of items on each page
    page = request.GET.get('page') # < Get the page number

    posts = paginator.get_page(page)
    products = Product.objects.all()
    context = {
        'products': products,
        'posts': posts
    }
    #return HttpResponse(products)
    return render(request,'best/category.html',context)
def signIn(request):
    return render(request,'best/SignIn.html')
def signUp(request):
    return render(request,'best/SignUp.html')
def manageCustomer(request):
    customers = Customer.objects.all()
    context = {
        'customers': customers
    }
    return render(request,'best/ManageCustomers.html',context)

def addCustomer(request):
    return render(request,'best/addCustomer.html')

def addUser(request):
    print(request.POST)
    cust_name = request.POST["cname"]
    cust_email = request.POST.get('cemail')
    cust_password = request.POST.get('cpassword')
    cust_country = request.POST.get('ccountry')
    cust_address = request.POST.get('caddress')
    cust_phoneNo = request.POST.get('cphoneNo')
    cust_postalCode = request.POST.get('cpostalCode')
    Add_customer = Customer(Cust_name=cust_name, Cust_email=cust_email, Cust_password=cust_password,
     Cust_country=cust_country, Cust_address=cust_address,Cust_phoneNo=cust_phoneNo, Cust_postalCode=cust_postalCode)
    Add_customer.save()
    #return HttpResponse('OK')
    return redirect('/ManageCustomers.html')
def edit(request, id):
    customer = Customer.objects.get(pk=id)
    context = {
        'customer': customer
    }
    return render(request, 'best/editCustomer.html', context)
def update(request, id):
    print(request.POST)
    customers = Customer.objects.get(pk=id)
    customers.cust_name = request.POST['custname']
    customers.cust_email = request.POST['custemail']
    customers.cust_password = request.POST['custpassword']
    customers.cust_country = request.POST['custcountry']
    customers.cust_address = request.POST['custaddress']
    customers.cust_phoneNo = request.POST['custphoneNo']
    customers.cust_postalCode = request.POST['custpostalCode']
    customers.save()
    return redirect('/')
    

polls/templates/change_list_graph.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("gender-chart");
            {% regroup cl.queryset|dictsort:"gender" by get_gender_display as gender_list %}
            var lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for gender in gender_list %}'{{ gender.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for gender in gender_list %}'{{ gender.list|length }}',{% endfor %}],
                        backgroundColor: [{% for gender in gender_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options: options
            });
            ctx = document.getElementById("language-chart");
            {% regroup cl.queryset|dictsort:"grades" by grades as grades_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for grade in grades_list %}'{{ grade.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for grade in grades_list %}'{{ grade.list|length }}',{% endfor %}],
                        backgroundColor: [{% for grades in grades_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
            ctx = document.getElementById("grades-chart");
            {% regroup cl.queryset|dictsort:"language" by get_language_display as language_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for language in language_list %}'{{ language.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for language in language_list %}'{{ language.list|length }}',{% endfor %}],
                        backgroundColor: [{% for language` in language_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
        }
    </script>
{% endblock %}
{% block content %}
    <h1> Graphs </h1>
    <hr>
    <div class="row">
        <div class="col-sm-4">
            <canvas id="gender-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="language-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="grades-chart" style="width: 100px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

polls/templates/change_list_graphCart.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        
        window.onload = function () {
            var ctx = document.getElementById("product-chart");
            {% regroup cl.queryset|dictsort:"P_id.P_id" by P_id as product_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for P_id in product_list %}'
                    {{ P_id.grouper }}
                    ',{% endfor %}],
                    datasets: [{
                        data: [{% for P_id in product_list %}'{{ P_id.list|length }}',{% endfor %}],
                        backgroundColor: [{% for P_id in product_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
             ctx = document.getElementById("cust-chart");
           
            {% regroup cl.queryset|dictsort:"Cust_id.Cust_id" by Cust_id as cust_list %}
            
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for Cust_id in cust_list %}'{{ Cust_id.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for Cust_id in cust_list %}'{{ Cust_id.list|length }}',{% endfor %}],
                        backgroundColor: [{% for Cust_id` in cust_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
        }
    </script>
{% endblock %}
{% block content %}
    <h1> Graphs </h1>
    <hr>
    <div class="row">
        <div class="col-sm-6">
            <canvas id="product-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-6">
            <canvas id="cust-chart" style="width: 100px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

polls/templates/change_list_graphProduct.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        
        window.onload = function () {
            var ctx = document.getElementById("language-chart");
            {% regroup cl.queryset|dictsort:"P_name" by P_name as name_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for P_name in name_list %}'{{ P_name.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for P_name in name_list %}'{{ P_name.list|length }}',{% endfor %}],
                        backgroundColor: [{% for P_name in name_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
           
           ctx = document.getElementById("grades-chart");
           
            {% regroup cl.queryset|dictsort:"P_price" by P_price as cat_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for P_price in cat_list %}'{{ P_price.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for P_price in cat_list %}'{{ P_price.list|length }}',{% endfor %}],
                        backgroundColor: [{% for P_price` in cat_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
        }
    </script>
{% endblock %}
{% block content %}
    <h1> Graphs </h1>
    <hr>
    <div class="row">
        <div class="col-sm-6">
            <canvas id="grades-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-6">
            <canvas id="language-chart" style="width: 100px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}